version: "3.7"

services:
    go-docker-env:
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        # command: go run main.go
        container_name: 'go-docker-env'
        # entrypoint: zsh -c "while sleep 1000; do :; done"
        environment:
            - TZ=
        build:
            # This allows us to access higher up files
            context: ..
            dockerfile: .devcontainer/Dockerfile
        labels:
            com.jordan-kadish.go-docker-env: "basic dockerised Golang env"
        ports:
            - "3000:3000"
        volumes:
            # - ../:/workspace
            # :ro below means "read-only"
            - ~/.ssh:/home/go-docker-env/.ssh:ro
            - ~/.ssh:/root/.ssh:ro
            - /var/run/docker.sock:/var/run/docker.sock
        working_dir: /workspace
        # links:
        #     - redis
        # networks: 
            # - dev-network
        # redis:
    #     image: redis:alpine
# networks: 
#     dev-network:
#         driver: bridge
